version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres:14.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
  nestjs:
    container_name: nestjs
    build:
      context: ./
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
